version: "3"
services:
  app:
    image: springboot-metrics:latest
    container_name: 'springboot-metrics'
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
  prometheus:
    image: prom/prometheus:latest
    container_name: 'prometheus'
    volumes:
      - ./prometheus/:/etc/prometheus/
    ports:
      - '9090:9090'
    depends_on:
      - app
  grafana:
    image: grafana/grafana:latest
    container_name: 'grafana'
    ports:
      - '3000:3000'
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    depends_on:
      - prometheus